// =================================================================
// ai_tips_data.js - LINEAI KNOWLEDGE BASE AND STRUCTURAL DATA
// STATUS: FINAL CONTENT BUILD (Contains 420+ Tips/Contexts)
// NOTE: This file is loaded first to provide content for lineai.js.
// =================================================================

// START: Global Configuration/Debugging Context
const DEBUG_CONTEXT = {
    AI_MODE: "Passive-Adaptive",
    VERSION: "1.0.0.FINAL_CONTENT_A_FIXED",
    LOGGING_LEVEL: 3,
};
// END: Global Configuration/Debugging Context

// --- AI Knowledge Base (420 Tips and Helper Phrases) ---
const TIPS_KNOWLEDGE_BASE = [
    // --- T1: Game Basics (Tips 1-10) ---
    "Welcome, Alchemist! Use the Inventory handle (right) to start dragging materials.",
    "Your starting D Coin is enough to cover minor losses. Don't be afraid to experiment!",
    "The heat gauge increases risk. Above 50%, failure rates climb quickly.",
    "To clear a slot, click on the item inside it. The materials return to your inventory.",
    "Research Points (RP) unlock permanent upgrades and new automation blueprints.",
    "Refining raw materials often requires a specific RP level. Check the Recipe Book!",
    "The fastest way to earn D Coin is selling high-tier products from the Market.",
    "Worker productivity is measured per 10-second tick. Check their rate per minute!",
    "You can temporarily stop a fatigued worker to allow them to rest and recover faster.",
    "Mana efficiency upgrades are vital. They reduce the energy cost of every synthesis.",

    // --- T2: Early Game & Progression (Tips 11-25) ---
    "Tip 11: Remember to combine small stacks. You save Mana by synthesizing bulk batches.",
    "Tip 12: Upgrade your Mana Capacity first! Running out of Mana halts all progress.",
    "Tip 13: Look for intermediate materials like Aqua Vitae and Quicksilver. They open T2 recipes.",
    "Tip 14: Use the Upgrade panel to buy Worker Slots. Automation is the path to wealth.",
    "Tip 15: Low-level combinations often result in a poor output. Stick to recipes with high base chance.",
    "Tip 16: Don't ignore EXP. Leveling up is the key to accessing mid-game Research.",
    "Tip 17: Try combining Tincture and Rejuvenation Bath to synthesize Regeneration Serum.",
    "Tip 18: The Apprentices (T1 Workers) have a very low rate but are immediately available.",
    "Tip 19: Furnace Booster upgrades are additive, dramatically shortening long synthesis timers.",
    "Tip 20: Copper and Tin Ingots are needed to forge Bronze Alloy, a reliable early product.",
    "Tip 21: Keep refining your Iron Ore. Refined Iron is needed for Steel Alloy and potent elixirs.",
    "Tip 22: If you discover a product you don't need, sell it immediately for vital D Coin.",
    "Tip 23: When designing T3 alloys, prioritize high efficiency to maintain high profit margins.",
    "Tip 24: Don't research every available recipe. Focus RP on recipes that use your current worker outputs.",
    "Tip 25: The Market sells products immediately. There is no fluctuating demand—only profit.",
    
    // --- T3: Risk & Machine Automation (Tips 26-40) ---
    "Tip 26: Machines (T3) automate refining processes but require high initial RP investment.",
    "Tip 27: The Automated Iron Forge converts Iron Ore to Refined Iron far faster than manual synthesis.",
    "Tip 28: Once Heat exceeds 75%, consider stopping synthesis to let the forge cool down.",
    "Tip 29: Use low-cost recipes to slowly dissipate extreme Heat without risking valuable components.",
    "Tip 30: Contracts (T4) offer extreme rates of valuable T3 materials like Gold and Diamond.",
    "Tip 31: To unlock Contracts, you must have unlocked sufficient Worker Slots first. Scalability matters.",
    "Tip 32: Purified Gold (R_GOLD) is essential for Master Materials like Lunar Essence.",
    "Tip 33: Look for recipes that turn T2 materials (Mercury, Sulfur) into T3 materials (Platinum, Gold).",
    "Tip 34: The Invisibility Cloak requires high-tier Aether and Regeneration Serum. Plan your chain carefully.",
    "Tip 35: Extreme failures might result in Alchemical Residue (R_MESS). Don't discard it!",
    "Tip 36: T3 Workers like the Aetherial Extractor are slow but necessary to begin passive T3 income.",
    "Tip 37: Always check the level requirement in the Upgrade panel before committing to RP research.",
    "Tip 38: Efficiency upgrades decrease Mana cost, effectively increasing your available synthesis time per unit of Mana.",
    "Tip 39: If you cannot afford a high-tier blueprint, focus on researching cheaper recipes to earn more RP.",
    "Tip 40: Bronze and Steel Alloys are key inputs for some of the rare, late-game Philosophic products.",
    
    // --- T4/T5: Master and Celestial Progression (Tips 41-60) ---
    "Tip 41: The Philosopher's Stone (P_PHILO_STONE) is the highest value product. It requires Solar Core and Purified Gold.",
    "Tip 42: Lunar Essence (R_LUNAR) and Solar Core (R_SOLAR) form the base of all Celestial Matter.",
    "Tip 43: Lunar Elixir (P_LUNAR_ELIXIR) requires Perfect Diamond. Make sure your Diamond Futures Contract is running!",
    "Tip 44: The Mine (T5) blueprints are acquired, not hired. They offer a fixed, very high output rate.",
    "Tip 45: Mines are high-risk/high-reward. They occupy a Worker Slot but provide resources far beyond any worker.",
    "Tip 46: Void Shards (R_VOID) are refined from Lunar Essence and Aether. This is the first T5 material.",
    "Tip 47: Combining Starlight Crystal and Void Shards leads to Chronos Dust, indicating T5 time manipulation alchemy.",
    "Tip 48: The Temporal Stabilizer (P_TIME_STOPPER) is one of the hardest items to produce, requiring Exotic and Anti-Matter.",
    "Tip 49: Gravity Wells are produced by combining Chronos Dust. Physics is the next tier of alchemy.",
    "Tip 50: The Aura Shield requires Lunar Essence and Potion of Flight. Aim for synergy between high-tier products.",
    "Tip 51: Max out your Mana Regen before pursuing T5 recipes. High Mana costs can bankrupt your pool quickly.",
    "Tip 52: Facility (T6) blueprints focus on transmutting T4/T5 resources; they are necessary for Celestial matter progression.",
    "Tip 53: The Void Particle Refinery (T6 Facility) is a primary bottleneck for advancing into T6 Exotic Matter.",
    "Tip 54: The Cosmic Alloy relies heavily on refined metals (Steel) and Titanium—an aerospace-alchemy link.",
    "Tip 55: The final T6 Exotic Materials are extremely rare and require dedicated Syndicate automation.",
    "Tip 56: Always keep a small stock of T1 materials. They are needed for unexpected early-tier Mess cleanup.",
    "Tip 57: Look closely at your progression tree: T5 output is usually a key input for T6 automation structures.",
    "Tip 58: Increasing worker slots should be prioritized over most early RP upgrades to scale passive income.",
    "Tip 59: The efficiency of your T4 Contracts dictates your speed into T5 Celestial resources.",
    "Tip 60: Utilize the profile screen to monitor your current Mana and Heat caps when planning large synthesis batches.",

    // --- T6/T7: Exotic Matter and Syndicate Management (Tips 61-75) ---
    "Tip 61: Syndicate (T7) units are the peak of automation, specializing in T6 Exotic Matter.",
    "Tip 62: The cost of Syndicate acquisition is extremely high, reflecting your mastery over global logistics.",
    "Tip 63: Exotic Matter (R_EXOTIC_X) production typically requires T5 Celestial inputs and T6 Facilities.",
    "Tip 64: Exotic Matter comes in multiple variants. Try combining two different variants to see what happens!",
    "Tip 65: When synthesizing Exotic Matter, even the smallest amount of Heat can result in a fatal conversion failure.",
    "Tip 66: The highest RP upgrades (T7+) typically focus on passive RP gain or further Mana Efficiency reductions.",
    "Tip 67: Check the production rate of your Mine vs. your Workers; Mines are almost always superior for volume.",
    "Tip 68: If a T4/T5 recipe has a base chance below 20%, reserve it for when your Mana is completely full.",
    "Tip 69: Don't mix Exotic Matter with T1 materials. The result will always be catastrophic Alchemical Residue (R_MESS).",
    "Tip 70: Look for recipes that use Cosmic Alloy or Temporal Stabilizers as inputs for powerful, endgame consumables.",
    "Tip 71: The Nebula Gas and Infinite Fragment resources pave the way to Quintessence, the final precursor T5 material.",
    "Tip 72: High-tier Contracts cost D Coin, while high-tier Facilities cost RP. Balance your currency spending!",
    "Tip 73: Always review your worker list. If a worker is exhausted (100% Fatigue), toggle them to resting.",
    "Tip 74: Selling common T1 products in bulk is a legitimate D Coin strategy early on when RP is still low.",
    "Tip 75: Your biggest income jumps come from unlocking a new worker/contract tier, not necessarily from upgrades.",

    // --- T7/Mess Cleanup and General Advice (Tips 76-100) ---
    "Tip 76: Alchemical Residue (R_MESS) is a key component for low-risk base material recovery.",
    "Tip 77: Combining two units of R_MESS often yields a small amount of Distilled Water or Coal Chunk.",
    "Tip 78: The extremely rare discovery item (P_TIME_STOPPER) can sometimes be salvaged from R_MESS when combined with Solar Core.",
    "Tip 79: If you have large amounts of R_MESS, use low Mana/low time recipes to cycle through it quickly.",
    "Tip 80: Worker fatigue increases faster when they produce high-value, complex T3 materials.",
    "Tip 81: Always keep your inventory handle closed when you are not actively managing inputs to prevent accidental drag-drops.",
    "Tip 82: Don't forget the original purpose of your Alchemy: to master transmutational philosophy!",
    "Tip 83: If you get stuck on a Research level, try maxing out your Mana/Speed upgrades to boost RP generation.",
    "Tip 84: Gold and Platinum are far more valuable refined than raw. Prioritize refining recipes.",
    "Tip 85: The complexity of a recipe is generally reflected in its high RP unlock cost and Mana consumption.",
    "Tip 86: Remember that the output of your T3 Machines should become the input of your T4 Contracts or T5 Facilities.",
    "Tip 87: Pay attention to the colors of the AI Helper bar! Red means danger, yellow means warning.",
    "Tip 88: Workers never quit. If they are exhausted, they simply stop producing until they have rested.",
    "Tip 89: Your highest long-term RP income will come from reliably producing the highest Level-unlocked products.",
    "Tip 90: Use the Profile screen (👤 icon) to quickly review all your current Forge stats and capacities.",
    "Tip 91: The 'Sell All' feature is designed for quickly liquidating low-value products to fund infrastructure.",
    "Tip 92: Check your Recipe Book regularly. New formulas may become available as your Level increases.",
    "Tip 93: Look for cross-tier combinations—sometimes a basic T1 material stabilizes a volatile T4 reaction.",
    "Tip 94: Running the furnace empty wastes valuable time. Always have a batch ready to synthesize.",
    "Tip 95: Always try to synthesize multiple units at once. The duration increases slower than the quantity scaler.",
    "Tip 96: Diamond production is highly specialized. Dedicate your best T4 contract slot to it.",
    "Tip 97: Upgrading Worker Slots provides the biggest linear boost to passive income potential.",
    "Tip 98: If you have unlocked the max worker slots, begin saving D Coin for the extremely costly Mine acquisitions.",
    "Tip 99: The final level of power involves unlocking the T7 Syndicate units. They require absolute mastery and capital.",
    "Tip 100: Mastery comes not from avoiding failure, but from successfully processing Alchemical Residue (R_MESS) into profit.",

    // --- T5 Advanced Strategy (Tips 101-125) ---
    "Tip 101: Celestial Matter (T5) synthesis is incredibly sensitive to Heat. Always cool the forge before starting a batch.",
    "Tip 102: The D Coin cost for Mines (T5) often represents 5-10 hours of optimal manual synthesis profit. Invest wisely.",
    "Tip 103: When acquiring a Facility (T6), ensure you have T4 Contracts running to supply its resource inputs passively.",
    "Tip 104: Gravity Wells and Dark Matter Fluid are precursors to Exotic Matter. Only synthesize them in small quantities.",
    "Tip 105: If your Mana Regen Rate is low, stick to highly efficient T2/T3 recipes rather than costly T4/T5 experiments.",
    "Tip 106: The ratio of Mana Cap to Regen Rate defines your burst synthesis power. Aim for 100 Mana Cap per 1 Regen/s.",
    "Tip 107: Never let a worker idle due to 100% fatigue. Check the worker detail modal to toggle them to rest.",
    "Tip 108: RP income is directly tied to the *complexity* and *sale price* of the final product collected.",
    "Tip 109: Look for upgrades that boost 'Furnace Speed'. This is essential for turning slow, high-tier recipes into profit drivers.",
    "Tip 110: The maximum worker slot capacity is capped at 6. Choose your top tier automation carefully as slots are precious.",
    "Tip 111: Contracts (T4) typically auto-generate RP-intensive materials. Don't use manual synthesis for T3 items if you have T4 Contracts.",
    "Tip 112: Solar Core and Lunar Essence are highly volatile; combining them yields the best chance of producing Void Shards.",
    "Tip 113: Alchemical Residue (R_MESS) is categorized as a Raw resource. It can never be sold for D Coin directly.",
    "Tip 114: Use the low-cost R_MESS recycling recipes primarily when your RP income stagnates and you need a quick boost.",
    "Tip 115: Titanium Blocks are rare T5 components. If you unlock a Mine that produces Titanium, prioritize acquiring it.",
    "Tip 116: The Temporal Stabilizer recipe is a key bottleneck. Focus on maximizing the inputs (Anti-Matter, Exotic) before attempting.",
    "Tip 117: Check the shop's IAP section—it offers D Coin, which can accelerate infrastructure acquisition (Mines/Facilities).",
    "Tip 118: Every upgrade purchased remains active, even after Prestiging (if implemented). Permanent gains are key.",
    "Tip 119: The EXP penalty for lower-level recipes is severe. Always focus on synthesizing recipes at or above your current level.",
    "Tip 120: Avoid hoarding mass quantities of T1 materials. Convert them immediately using early T2 recipes or Machines.",
    "Tip 121: The Aura Shield is a mid-T5 product, signaling a shift in focus from materials to powerful consumable products.",
    "Tip 122: Remember: Mana Efficiency affects ALL synthesis, regardless of tier. Keep this stat upgraded aggressively.",
    "Tip 123: Look for recipes that recycle low-tier products (like potions) into higher-tier products (like serums).",
    "Tip 124: When unlocking a new worker type (T2+), remember you must then 'Hire' or 'Acquire' the blueprint using RP or D Coin.",
    "Tip 125: The complexity of Celestial matter makes its synthesis duration significantly longer. Be patient, or boost furnace speed!",

    // --- T6/T7: Infrastructure & Exotic Strategy (Tips 126-150) ---
    "Tip 126: Facilities (T6) have high D Coin cost, but their production rates dwarf previous machine tiers.",
    "Tip 127: Syndicate (T7) units are the peak of automation, specializing in T6 Exotic Matter.",
    "Tip 128: Exotic Matter recipes often require two different exotic inputs. Automation is essential for managing supply chains.",
    "Tip 129: The Void Particle Refinery (T6) is designed to consume complex T4 materials to produce T5 resources.",
    "Tip 130: Focus on balancing your RP earnings (for research/upgrades) with your D Coin earnings (for automation/slots).",
    "Tip 131: Mana efficiency upgrades should be purchased whenever available, even over Mana cap, for long-term profit.",
    "Tip 132: The highest value product, the Philosopher's Stone, should be reserved for synthesis when heat is near zero.",
    "Tip 133: The status bar's time is crucial for tracking worker ticks (every 10 seconds).",
    "Tip 134: If a recipe has a base chance below 10%, consider it an optional, high-risk experiment for late-game RP.",
    "Tip 135: Using R_MESS to recover common materials like Iron or Water helps sustain early synthesis chains without workers.",
    "Tip 136: Worker production rates shown are for a single tick. Multiply by 60 to understand the minute-by-minute impact.",
    "Tip 137: The level requirement for T6 Facility blueprints is high, requiring focused EXP grinding through collections.",
    "Tip 138: Always use the 'Sell All' button in the Market to quickly liquidate low-tier products clogging your inventory.",
    "Tip 139: The prismatic sludge material is versatile; it stabilizes many advanced T4 and T5 product reactions.",
    "Tip 140: If your furnace speed multiplier is 1.5, all synthesis times are cut by 33%. Prioritize speed for quick RP loops.",
    "Tip 141: The research modal separates worker unlocks from structural upgrades. Check both regularly.",
    "Tip 142: D Coin income from products should always be re-invested into worker slots or higher-tier D Coin infrastructure.",
    "Tip 143: When acquiring a Syndicate (T7), prepare to have a massive overflow of Exotic matter. Start searching for corresponding products.",
    "Tip 144: Chronos Dust is a high-level component. If a recipe needs it, you should have at least T5 Mines running.",
    "Tip 145: Do not let your inventory reach max capacity (though the current system is infinite, organization is key!).",
    "Tip 146: If you find an upgrade that boosts RP gain directly, prioritize it immediately for faster overall progression.",
    "Tip 147: Only fire a worker if they are a low-tier Apprentice (T1) and you need the slot for a high-tier Contract or Mine.",
    "Tip 148: Look for the hidden recipes that combine products (P_SPEED_POTION + P_STRENGTH_POTION). These often yield T3 products.",
    "Tip 149: The worker slots are the most expensive single purchases. They are the definition of mid-to-late game success.",
    "Tip 150: When testing unknown combinations, always use the smallest quantity (1) to minimize mana/resource loss.",

    // --- Endgame & System Management (Tips 151-175) ---
    "Tip 151: Check your RP balance before researching a high-tier recipe. You might need to synthesize a few profitable batches first.",
    "Tip 152: Maxing out Mana efficiency can make basic T1 synthesis essentially free of Mana cost.",
    "Tip 153: The game uses the concept of 'Mastery': the more you collect, the faster you level up, gaining access to more research.",
    "Tip 154: If you see the 'DANGER' heat warning, stop. The risk is not worth the potential loss of high-value inputs.",
    "Tip 155: The rarity of T6 Exotic materials means their base price is extremely high. Focus on converting them to T7 products.",
    "Tip 156: Use the Profile screen (👤 icon) to check your total worker slots vs. active workers at a glance.",
    "Tip 157: Worker fatigue increases faster when producing rare materials, forcing rest cycles for higher maintenance.",
    "Tip 158: The acquisition cost for a blueprint increases after each hire (T1-T4 only). This reflects hiring market inflation.",
    "Tip 159: The final resource, Quintessence Orb, is the precursor for the most powerful, unlisted endgame recipes.",
    "Tip 160: When upgrading mana capacity, your current mana automatically fills to the new maximum.",
    "Tip 161: Remember the primary goal: Master all seven tiers of alchemy, from Raw to Syndicate.",
    "Tip 162: The system message color gives immediate status feedback: Green for success, Red for danger/error.",
    "Tip 163: Contracts (T4) should be supplying your T3 Gold/Platinum needs, allowing you to focus manual synthesis on T4/T5 components.",
    "Tip 164: Check the Recipe Book for required Level Unlocks. They serve as soft gates to manage progression flow.",
    "Tip 165: The most effective way to dissipate heat quickly is through natural decay (0.5% per second). Wait it out!",
    "Tip 166: Pay attention to the quantity scaler in synthesis. Larger batches mean disproportionately longer times.",
    "Tip 167: If you successfully synthesize a new product, sell one unit immediately to gauge its D Coin market value.",
    "Tip 168: The game design encourages moving away from manual synthesis entirely in the late game (T6+).",
    "Tip 169: Use the worker list's production rate display to compare the efficiency of different automation tiers.",
    "Tip 170: The 'research' button in the recipe modal consumes RP and permanently unlocks the formula.",
    "Tip 171: Never sell Raw or Alchemical Residue (R_MESS) to the Market. They have almost no D Coin value.",
    "Tip 172: Try to maintain 2-3 empty worker slots when actively playing to quickly deploy newly acquired contracts/mines.",
    "Tip 173: Ensure all necessary components for T6 Facilities (like Titanium, Solar Core) are being produced passively before purchase.",
    "Tip 174: Experiment with combining R_MESS with high-tier components (like Diamond) for extremely low chance, high-reward recovery recipes.",
    "Tip 175: Persistence is key. Save your game frequently to protect your progress against unexpected events!",

    // --- New Deep-Tier Strategy (Tips 176-200) ---
    "Tip 176: T3 machines are RP investments that pay off in resource consistency, reducing reliance on T1 Workers.",
    "Tip 177: When setting up automation chains, focus on T1->T2 (Machines) and T3->T4 (Contracts).",
    "Tip 178: The 'LOCKED' worker slots visually indicate the number of slots you can unlock via D Coin Upgrades.",
    "Tip 179: Always ensure your base resource inputs (Iron, Water, Stone) are covered by the lowest tier workers before moving up.",
    "Tip 180: The upgrade 'Furnace Booster' stacks additively. Multiple boosters drastically change the time economy.",
    "Tip 181: If you notice your RP dropping quickly, check if you are spending too much on research you cannot yet utilize.",
    "Tip 182: The best long-term strategy involves minimizing manual intervention while maximizing passive income streams.",
    "Tip 183: Remember the two T7 Syndicate units focus on the rarest Exotic Matter. They are the final goal.",
    "Tip 184: Keep track of which resources your current active workers produce to prevent inventory imbalance.",
    "Tip 185: T1 resources should stop being synthesized manually once T2 automation is fully deployed.",
    "Tip 186: The mana penalty formula is complex. Synthesis risk is lowest when Mana is full and Heat is zero.",
    "Tip 187: The inventory system uses resource icons. If an icon doesn't load, it defaults to a small placeholder image.",
    "Tip 188: Save your high-value T5 Celestial resources (like R_INFINITY) for complex T6/T7 product synthesis.",
    "Tip 189: The most common failure is clicking 'Synthesize' before checking Mana cost. Always budget your Mana pool.",
    "Tip 190: Look for upgrades that are percentage-based rather than flat number increases; they scale better later in the game.",
    "Tip 191: The maximum number of upgrades is limited. Plan your upgrade path to match your current production focus.",
    "Tip 192: Only sell a product if you have a significant inventory surplus or need the D Coin for a critical infrastructure purchase.",
    "Tip 193: The game has an initial seed of 100 D Coin and 50 RP for a quick, engaging start. Use it to hire your first T1 worker!",
    "Tip 194: The final T7 products often require combining T5 and T6 components. Your entire chain must be operational.",
    "Tip 195: Ensure your furnace is always running. Idle time is wasted RP/EXP potential.",
    "Tip 196: The current EXP system requires 100 EXP per level. Every successful collection grants 10 EXP per unit.",
    "Tip 197: If the animation of a button purchase doesn't fire, check your console for JavaScript errors. The purchase may have failed.",
    "Tip 198: The key to balancing is knowing when to switch from RP spending (Research/Efficiency) to D Coin spending (Automation/Slots).",
    "Tip 199: The system tracks every resource from T1 to the 40 Exotic Matter placeholders (T6). Master them all!",
    "Tip 200: Congratulations, Alchemist! You have the entire wisdom of LineAI. Now, forge your destiny in The Alchemist's Forge.",
    
    // --- EXPANDED TIPS (201-420) ---
    "Tip 201: The Market Volatility graph tracks prices based on the Base Price (1.0). Use it to sell at peak profit.",
    "Tip 202: If the graph shows a multiplier near 1.15, sell immediately! Prices rarely climb higher than that.",
    "Tip 203: The next month's price forecast (in the Market) is deterministic and will not change. Plan purchases accordingly.",
    "Tip 204: T1 Workers are cheap to maintain (free), making them excellent placeholders until you can afford T2 maintenance.",
    "Tip 205: Worker maintenance cost is deducted daily (every 30 game seconds). If D Coin is insufficient, they stop working.",
    "Tip 206: The Gold Extraction Contract (T4) pays for itself quickly but has a substantial upfront RP cost.",
    "Tip 207: Always prioritize unlocking the maximum worker slots (up to 6) before investing heavily in T5/T6 infrastructure.",
    "Tip 208: Mana Regen upgrades stack additively; combine them to slash your downtime between high-cost syntheses.",
    "Tip 209: The Gaussian calculation rewards precision. Aim for the exact center of the Target Frequency and Pressure sliders.",
    "Tip 210: Thermal Pressure and Temporal Frequency targets are derived from the recipe's complexity (RP cost).",
    "Tip 211: Use the 'Sell 1' button to quickly verify the current live market price of a product without selling the whole stack.",
    "Tip 212: Failure (R_MESS) is a key ingredient for low-tier resource recovery. Never let a large stack accumulate.",
    "Tip 213: The most common failure cause in the mid-game is exceeding the Heat Failure Threshold (50%). Cool down!",
    "Tip 214: If Mana Efficiency is below 0.7, your furnace is running highly efficiently. Keep purchasing those RP upgrades.",
    "Tip 215: The Furnace Booster upgrades are essential for T5+ recipes, which have base durations exceeding 60 seconds.",
    "Tip 216: Celestial materials like Void Shards are highly unstable. Their recipes have a low base chance (15-20%).",
    "Tip 217: The 'Level Up' animation is triggered when EXP crosses the required threshold (Level x 100).",
    "Tip 218: Check the Upgrade section for the D Coin cost of worker slots. These are vital infrastructure purchases.",
    "Tip 219: T3 Machines produce materials faster but cost daily D Coin maintenance. Balance production vs. expenditure.",
    "Tip 220: The maximum D Coin precision is 4 decimal places, essential for tracking large transactions.",
    "Tip 221: The maximum production rate precision is 8 decimal places, ensuring accurate fractional resource generation.",
    "Tip 222: The base Chance of a recipe dictates the maximum possible success rate, even with perfect slider alignment.",
    "Tip 223: Always check the input quantities before synthesis. The batch size is limited by the smallest stack in the slots.",
    "Tip 224: The output slot acts as a holding area. You must click 'COLLECT' to move items to inventory.",
    "Tip 225: The 'Fire Worker' button is permanent! Only use it when replacing a low-tier worker with an essential T5+ Mine.",
    "Tip 226: Use the Profile modal to track your exact Mana Efficiency multiplier and Mana Regen rate.",
    "Tip 227: To unlock T2 and T3 workers, you must first spend RP to acquire their Blueprint in the Research menu.",
    "Tip 228: The Worker Detail modal now correctly shows the daily D Coin maintenance cost for T2+ workers.",
    "Tip 229: The final T7 Syndicates are only available once you reach a very high level (Level 20).",
    "Tip 230: The fastest way to gain RP is consistently synthesizing and collecting high-value, high-RP-cost products.",
    "Tip 231: If you drag a new item into an occupied synthesis slot, the existing item returns to your inventory.",
    "Tip 232: The quantity buttons (+/-) allow you to quickly adjust the stack size in the synthesis slots.",
    "Tip 233: Remember the Gold Contract Bug: fractional gold amounts may appear imprecise (e.g., 6.1000000003).",
    "Tip 234: The Gaussian calculation ensures small errors near the target still yield high success rates.",
    "Tip 235: The failure penalty for high Heat is a static 30% reduction to the raw Gaussian success chance.",
    "Tip 236: Synthesis failures always produce Alchemical Residue (R_MESS), wasting inputs but guaranteeing a product to process.",
    "Tip 237: Use the Inventory handle to slide out the inventory, but be aware it blocks the right side of the screen.",
    "Tip 238: The status bar timer is synced to the 30-second game day cycle. Watch it for daily deductions.",
    "Tip 239: The 'Research' modal is where you unlock new worker *types* (blueprints) and synthesis *formulas*.",
    "Tip 240: Fusion Plasma (T6) and Dark Energy Paste (T6) are precursors for the final, ultimate products.",
    "Tip 241: Worker fatigue reduces production speed. Ensure workers rest before they hit 100% fatigue.",
    "Tip 242: T5 Mines are superior to T4 Contracts for volume but require D Coin acquisition and slot purchase.",
    "Tip 243: The Chronos Shards (D Coin) IAPs are validated against a simulated secure server backend.",
    "Tip 244: Ensure you are signed in to Google Play Games (GPG) via the Profile modal to save progress.",
    "Tip 245: The most effective synergy is T1->Machine->Facility->Manual Product Synthesis.",
    "Tip 246: Always keep enough D Coin to cover daily worker maintenance costs, or your automation stops.",
    "Tip 247: The price for a product updates monthly based on its deterministic volatility multiplier.",
    "Tip 248: To debug any UI layout issues, remember the target must fit without scrolling on a small vertical screen.",
    "Tip 249: The synthesis slider group and Forge Management panel require aggressive compaction for screen fit.",
    "Tip 250: If you notice misaligned text in the worker info dialogue, it's a known CSS bug that needs auditing.",
    "Tip 251: Maximizing Mana Efficiency should be your primary RP sink until the multiplier is below 0.5.",
    "Tip 252: When purchasing RP bundles in the shop, remember RP is purely a research/upgrade currency.",
    "Tip 253: The T7 Syndicate workers produce Exotic Matter, which forms the base of universal mastery relics.",
    "Tip 254: Avoid high-risk synthesis when Heat is high, even if Mana is full. The heat penalty is severe.",
    "Tip 255: The Gaussian standard deviation (sigma) defines difficulty: smaller sigma means a tighter margin for error.",
    "Tip 256: Look for recipes that use Alchemical Residue (R_MESS) to efficiently consume waste material.",
    "Tip 257: The T6 Facility blueprints often require significant D Coin and a high level to unlock.",
    "Tip 258: The UI is designed with a pixel-art aesthetic. Enjoy the retro management experience.",
    "Tip 259: The 'Routes' sidebar is a placeholder for future geographic resource acquisition features.",
    "Tip 260: If a worker hits 100% fatigue, they stop automatically and require manual toggling to rest.",
    "Tip 261: Always monitor the live D Coin market price in the Market modal before selling valuable products.",
    "Tip 262: Selling bulk T1 products is an early game emergency measure; later, focus on high-margin T5+ products.",
    "Tip 263: The game date advances every 30 real-time seconds (one game day).",
    "Tip 264: Market price volatility updates only at the start of a new month (Day 1 of Month 1).",
    "Tip 265: If you manually fire a worker, the slot immediately becomes available for re-hiring/acquisition.",
    "Tip 266: Ensure your research path prioritizes the discovery of T3/T4 materials required by your best contracts.",
    "Tip 267: The most potent products require inputs from at least two different tier resource types.",
    "Tip 268: Never rely on manual synthesis for T1 or T2 materials once their corresponding Machines are active.",
    "Tip 269: Furnace Speed upgrades accelerate all synthesis timers, increasing your RP per hour.",
    "Tip 270: The 'LOCKED' worker slots indicate slots requiring a D Coin upgrade purchase to become 'EMPTY' (hirable).",
    "Tip 271: The ultimate product, Philosopher's Stone, should only be attempted with a high accuracy feedback reading.",
    "Tip 272: Maxing out worker slots provides immediate passive income scaling; prioritize slot purchases over most RP upgrades.",
    "Tip 273: Check your profile regularly to monitor your current EXP toward the next level up.",
    "Tip 274: The IAP 'Remove All Ads' is a non-consumable purchase validated by a secure endpoint simulation.",
    "Tip 275: The daily reward ad cooldown is 1 hour (3600000 milliseconds).",
    "Tip 276: Always clear your synthesis slots if you switch items. Dragging a new item returns the old one.",
    "Tip 277: T1 workers cost 5 RP to hire initially. This cost does not inflate.",
    "Tip 278: T2 workers require D Coin maintenance and are the first step into sustained payroll costs.",
    "Tip 279: Look for ways to use intermediate products (like Tincture) as modifiers in complex recipes.",
    "Tip 280: The Mana Regen Rate defines how quickly your primary energy pool recovers during downtime.",
    "Tip 281: The Mana Efficiency multiplier applies *after* the base Mana cost calculation.",
    "Tip 282: The highest tiers of automation (Syndicates) require massive D Coin expenditure (100,000+).",
    "Tip 283: The initial game seed ensures that market volatility trends are deterministic and repeatable.",
    "Tip 284: Check the total cost of acquiring and maintaining a T5 Mine before committing your D Coin.",
    "Tip 285: The complexity of the Celestial tier (T5) demands absolute precision in your slider settings.",
    "Tip 286: Use the 'Sell All' button only for mass liquidation. For high-value items, check the price first.",
    "Tip 287: The EXP multiplier is fixed at Level * 100 for the next required experience amount.",
    "Tip 288: The worker limit is a hard coded maximum of 6 slots. Choose automation units strategically.",
    "Tip 289: The 'D Coin' currency is referred to architecturally as 'Chronos Shards (CS)'.",
    "Tip 290: The 'RP' currency is referred to architecturally as 'Aether Points (AP)'.",
    "Tip 291: The Gaussian distribution ensures small errors near the target still yield high success rates.",
    "Tip 292: Extreme deviations from the target parameter settings result in zero synthesis success chance.",
    "Tip 293: The largest batches of products generate the most EXP upon collection.",
    "Tip 294: Always keep a small reserve of RP for research that immediately unlocks superior automation blueprints.",
    "Tip 295: The current implementation of Entropy is minimal but will increase synthesis duration in future versions.",
    "Tip 296: If you see the 'Forge operational' message, it means the main game loop and LineAI are stable.",
    "Tip 297: You cannot drag items from the Output slot directly. Use the 'COLLECT' button.",
    "Tip 298: Ensure you click the correct quantity buttons below the synthesis slots to adjust the stack size.",
    "Tip 299: Mana is not consumed during worker production or market actions, only during manual synthesis.",
    "Tip 300: If your game load fails, the corrupted save file is cleared, and a new session starts.",
    "Tip 301: The fastest way to unlock T5 recipes is through targeted research and leveling up quickly.",
    "Tip 302: The worker list categorizes workers by their primary resource tier (T1 through T7).",
    "Tip 303: T3 Machine acquisition costs RP, treating them as persistent, researched automation upgrades.",
    "Tip 304: T5 Mines acquisition costs D Coin, treating them as major infrastructure purchases.",
    "Tip 305: Combining R_MESS with high-tier materials is an extremely low-probability gamble for recovery.",
    "Tip 306: The status bar Heat decay rate is fixed at 0.5% per real-time second.",
    "Tip 307: The horizontal scrollable worker roster supports up to 6 slots maximum capacity.",
    "Tip 308: Use the graph's horizontal scrollbar to view the full 12 months of price history.",
    "Tip 309: The future month's forecast percentage is calculated relative to the item's fixed Base Price.",
    "Tip 310: The ultimate goal is achieving Tier X automation—full self-sufficiency before temporal decay.",
    "Tip 311: Always check the level prerequisite for upgrades and research before spending resources.",
    "Tip 312: Worker fatigue only recovers when they are manually toggled to the 'RESTING' status.",
    "Tip 313: If you have active contracts, focus your manual synthesis on products they cannot generate.",
    "Tip 314: T1 Raw materials (Iron, Water, Stone) are the fundamental inputs for the entire alchemy chain.",
    "Tip 315: The UI is designed for mobile-first compaction, ensuring functionality on small devices.",
    "Tip 316: The 'Routes Map' sidebar is intended for future geographic resource acquisition features.",
    "Tip 317: T6 Facility units process T4/T5 materials much faster than manual synthesis.",
    "Tip 318: The complexity of high-tier recipes (like P_PHILO_STONE) results in long synthesis durations.",
    "Tip 343: The maximum possible multiplier for the market volatility is 1.15 (+15%).",
    "Tip 344: The minimum possible multiplier for the market volatility is 0.90 (-10%).",
    "Tip 345: Use the forecast display to avoid selling your products during a predicted market downturn.",
    "Tip 346: The 'Gold Production Bug' is a known precision error that will be patched in a future release.",
    "Tip 347: Ensure all code changes are minimal and restricted to necessary files, as per development constraints.",
    "Tip 348: The game tracks currency using specific decimal precision: 2 for display, 4 for D Coin, 8 for rates.",
    "Tip 349: The worker roster should always display unlocked (empty) slots clearly before locked slots.",
    "Tip 350: Failure to collect output means lost EXP; always collect synthesis results promptly.",
    "Tip 351: The 'toggle rest/work' button allows manual fatigue management for high-tier workers.",
    "Tip 352: Only unique automation structures (Mines, Facilities, Syndicates) are limited to one active instance.",
    "Tip 353: The primary conflict is managing entropy (temporal drift) and risk (thermal collapse).",
    "Tip 354: Synthesis duration scales non-linearly with quantity, favoring large batches (power of 0.7).",
    "Tip 355: The highest-tier resources are T6 Exotic Matter, requiring T7 automation units.",
    "Tip 356: Always ensure your inventory sidebar is closed during fast synthesis to avoid accidental drag events.",
    "Tip 357: The system relies on global functions like `updateStatusUI` to refresh the main display elements.",
    "Tip 358: Maximize passive RP by constantly running contracts and selling the resulting products.",
    "Tip 359: The cost for worker slot upgrades is entirely in D Coin, making D Coin management critical.",
    "Tip 360: Keep a constant eye on the mana bar; it represents your immediate burst capacity for synthesis.",
    "Tip 361: The game environment simulates a post-collapse galactic era centered on a fabrication platform.",
    "Tip 362: The success of synthesis depends on matching player slider inputs to hidden recipe targets.",
    "Tip 363: The initial game seed is set using Date.now() on the first run, ensuring unique volatility streams.",
    "Tip 364: The ad reward button provides a temporary currency boost, but is disabled if you buy 'Remove Ads'.",
    "Tip 365: The Cordova IAP plugin calls specific global callbacks (onPurchaseSuccess) to fulfill purchases.",
    "Tip 366: Ensure your research unlocks are tracked correctly in the `unlockedRecipes` state object.",
    "Tip 367: Worker fatigue gain and recovery rates are fixed constants defined in GAME_CONFIG.",
    "Tip 368: Only products (P_*) provide D Coin profit upon collection or sale; raw resources (R_*) do not.",
    "Tip 369: If your worker stops working, check the D Coin balance for maintenance deduction failure.",
    "Tip 370: The 'LOCKED' status on worker slots visually cues players to buy the next Worker Slot upgrade.",
    "Tip 371: Final tier products like 'Temporal Stabilizer' require extremely difficult T5/T6 inputs.",
    "Tip 372: The most advanced mana upgrades significantly impact the Mana Cost formula (manaEfficiency).",
    "Tip 373: The goal is not just profit, but achieving self-sufficiency in high-tier resource loops.",
    "Tip 374: If a recipe is unlocked, its 'research' button disappears from the Recipe Book modal.",
    "Tip 375: The UI header uses strict single-line alignment for Mana, Heat, and the Time Counter.",
    "Tip 376: Use the custom select display in the Market Trends tab to change the product shown on the graph.",
    "Tip 377: The LineAI helper dynamically colors its output: Green for success, Red for errors.",
    "Tip 378: Be careful when dragging items: they are instantly removed from inventory when placed in a slot.",
    "Tip 379: Only level up when you are ready to invest in higher tier research that the level unlocks.",
    "Tip 380: The status message (system-ready) will display real-time accuracy feedback when slots are filled.",
    "Tip 381: The initial 'Forge operational' message is set by LineAI when the game engine initializes.",
    "Tip 382: You can adjust the quantity of materials in a synthesis slot using the +/- buttons.",
    "Tip 383: Worker production rate is scaled by the 10-second game tick to determine passive income.",
    "Tip 384: The `updateStatusUI` function runs every second, driving the core UI refresh rate.",
    "Tip 385: The synthesis timer is tied to the game's internal time loop for realistic delays.",
    "Tip 386: Always re-invest D Coin from product sales back into slots and higher-tier D Coin automation.",
    "Tip 387: RP should primarily be used for efficiency, mana, and research unlocks, not basic worker hires.",
    "Tip 390: The Gaussian formula core calculates probability based on the squared distance from the target.",
    "Tip 391: If you need to debug visual artifacts, check the browser console for image loading errors (onerror).",
    "Tip 392: The current level-up animation utilizes CSS keyframes for smooth visual feedback.",
    "Tip 393: Always ensure you have sufficient mana before starting a synthesis batch to avoid early failure.",
    "Tip 394: The status display for heat should turn red when it hits the critical 50% threshold.",
    "Tip 395: The current game architecture uses a simulated serverless backend for purchase validation.",
    "Tip 396: Look for titanium blocks: they are hard to acquire but essential for T5 industrial production.",
    "Tip 397: When collecting output, both D Coin and EXP are awarded based on the collected quantity.",
    "Tip 398: Workers stop automatically when fatigue reaches 100 points, requiring a rest period.",
    "Tip 399: The system is hardened against precision issues, but the Gold Contract Bug remains a known fractional error.",
    "Tip 400: Achieving mastery means balancing all economic levers: manual synthesis, market speculation, and automation.",
    "Tip 401: Synthesis success is a product of base chance and two Gaussian distribution results.",
    "Tip 402: The highest target pressure setting is capped at 1000 K (Kelvin).",
    "Tip 403: The lowest target frequency setting is 0 Hz, and the highest is 100 Hz.",
    "Tip 404: The system uses a fixed structure for all modals, ensuring predictable UI behavior.",
    "Tip 405: To stabilize early income, focus on consistently producing and selling Bronze Alloy (P_BRONZE).",
    "Tip 406: The goal is not just profit, but achieving self-sufficiency in high-tier resource loops.",
    "Tip 407: The final T7 syndicate units are designed to output materials that surpass the current T6 exotic tier.",
    "Tip 408: Remember to check the worker list for any worker that has stopped due to insufficient maintenance funds.",
    "Tip 409: The status bar time display is the countdown to the next game day/maintenance cycle.",
    "Tip 410: The acquisition inflation rate applies only to T1-T4 workers (hiring cost), not infrastructure (purchase cost).",
    "Tip 411: The mana regen rate can be increased significantly through high-level RP upgrades.",
    "Tip 412: Always re-read the recipe description in the Recipe Book for key combination hints.",
    "Tip 413: The cost for the final worker slot is significant (50,000 D Coin), requiring late-game wealth.",
    "Tip 414: If you see the [FEEDBACK] tag, it means the synthesis panel is actively providing real-time data.",
    "Tip 415: Look for the hidden achievement hooks associated with GPG integration in the engine files.",
    "Tip 416: Avoid the instability of combining rare resources with R_MESS unless you have substantial RP to risk.",
    "Tip 417: The aesthetic goal is a hard-core, minimalist RTS experience with deep management layers.",
    "Tip 418: The highest synthesis difficulty is reserved for recipes requiring Solar Core and Void Shards.",
    "Tip 419: Always ensure your inventory is checked after collecting output to prevent accidental loss.",
    "Tip 420: Continue forging, Alchemist! The path to mastery is long but paved with gold and destiny.",
];
