version: 1.0.0

trigger:
  branch:
    - master
    - main

workflows:
  android-alpha-build:
    name: Android Alpha Build (Cordova)
    instance_type: mac_mini_m2
    environment:
      java: 21
      node: 18
      vars:
        CORDOVA_ANDROID_VERSION: "12.0.0"

    scripts:
      - name: Install Cordova CLI
        script: |
          npm install -g cordova

      - name: Install Android SDK
        script: |
          brew install --cask android-commandlinetools || true
          export ANDROID_HOME="$HOME/Library/Android/sdk"
          export PATH="$ANDROID_HOME/cmdline-tools/latest/bin:$PATH"
          export PATH="$ANDROID_HOME/platform-tools:$PATH"
          echo "y" | sdkmanager --sdk_root=$ANDROID_HOME "platform-tools" "platforms;android-34" "build-tools;34.0.0" || true
          echo "y" | sdkmanager --licenses || true

      - name: Prepare Cordova Android Platform
        script: |
          if [ ! -d "platforms/android" ]; then
            cordova platform add android@$CORDOVA_ANDROID_VERSION
          else
            cordova prepare android
          fi

      - name: Build APK
        script: |
          cordova build android --debug

      - name: Locate & copy APK
        script: |
          APK_PATH=$(find platforms/android/app/build/outputs/apk/debug -name "*.apk" | head -1)
          echo "APK found at: $APK_PATH"
          cp "$APK_PATH" app-debug.apk

    artifacts:
      - app-debug.apk
      - platforms/android/app/build/outputs/**/*.apk
