workflows:
  android-debug:
    name: Cordova Android Debug Build
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      groups:
        - android_signing # ← optional, only if you ever want release builds later
      vars:
        CORDOVA_VERSION: "12.0.0"
        ANDROID_PLATFORM_VERSION: "34"
        ANDROID_BUILD_TOOLS: "34.0.0"
        CM_BUILD_DIR: $CM_BUILD_DIR
      node: latest
      xcode: latest
      cocoapods: default

    triggering:
      events:
        - push
        - tag
        - pull_request
      branch_patterns:
        - pattern: "*"
          include: true
          source: true
      tag_patterns:
        - pattern: "*"

    scripts:
      - name: Install Node dependencies & Cordova globally
        script: |
          npm install
          npm install -g cordova@$CORDOVA_VERSION

      - name: Install Android SDK tools & accept licenses
        script: |
          echo y | $ANDROID_HOME/tools/bin/sdkmanager --licenses > /dev/null
          $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager \
            "platform-tools" \
            "platforms;android-$ANDROID_PLATFORM_VERSION" \
            "build-tools;$ANDROID_BUILD_TOOLS" \
            "cmdline-tools;latest"

      - name: Prepare Cordova Android platform
        script: |
          cordova telemetry off
          cordova platform rm android --nosave || true
          cordova platform add android@12.0.1 --no-resources --fetch

      - name: Fix Gradle wrapper (Codemagic sometimes has old wrapper)
        script: |
          cd platforms/android
          if [ ! -f gradlew ]; then
            gradle wrapper --gradle-version 8.7 --distribution-type all
          else
            ./gradlew wrapper --gradle-version 8.7 --distribution-type all
          fi
          chmod +x gradlew
          cd ../..

      - name: Build Debug APK
        script: |
          cordova build android --debug --verbose --device

    artifacts:
      - platforms/android/app/build/outputs/apk/debug/app-debug.apk
      - $CM_BUILD_DIR/build/**/**/*.apk

    publishing:
      email:
        recipients:
          - your-email@example.com   # ← change or remove if you don’t want emails
        notify:
          success: true
          failure: true
