# 1. MANDATORY ROOT KEY: Defines the YAML version
version: 1.0.0
trigger:
  branch:
    - master
    - main

# 2. MANDATORY ROOT KEY: Defines the build pipelines
workflows:
  android-alpha-build:
    name: Android Alpha Build (Cordova - No GPG)
    instance_type: mac_mini_m2
    environment:
      java: 21 
      node: 18
      vars:
        # Set the target Cordova Android version
        CORDOVA_ANDROID_VERSION: "12.0.0" 
# --- Build Steps (FINAL, MINIMALIST SEQUENCE) ---
    scripts:
      - name: Install Cordova CLI
        script: npm install -g cordova

      - name: Add Android Platform
        # This command must be run from the repository root (where config.xml should be located).
        # We assume the user has placed a valid config.xml file in the repository root.
        script: cordova platform add android@$CORDOVA_ANDROID_VERSION
          
      - name: Build the Android Debug APK
        script: |
          # The compilation command runs from the root.
          cordova build android --debug
          
          # CRITICAL FIX: Locate and copy the APK file. We use a search to confirm the path, then copy it.
          echo "Attempting to locate and copy the generated APK file..."
          
          APK_PATH=$(find platforms/android/ -name "app-debug.apk")
          
          if [ -f "$APK_PATH" ]; then
            echo "SUCCESS: Found APK at $APK_PATH"
            # Copy the found APK to the root directory for Codemagic to pick up
            cp "$APK_PATH" .
          else
            echo "ERROR: Failed to locate app-debug.apk after build. Build failed earlier."
            exit 1 # Fail the script if the APK is not found
          fi
          
    # --- Artifacts (Output) ---
    artifacts:
      - "*.apk"

      - platforms/android/app/build/outputs/**/*.apk
      
