# --- Build Steps (FINAL CORRECTED SEQUENCE) ---
    scripts:
      - name: Install Cordova CLI
        script: npm install -g cordova

      - name: Initialize Cordova Project and Copy Files
        script: |
          # 1. Create the project structure in a temporary folder named 'temp_app'
          cordova create temp_app com.forge.alchemist "The Alchemist's Forge"
          
          # 2. Change directory into the newly created project (THIS IS THE KEY)
          cd temp_app
          
          # 3. Delete the boilerplate www folder created by Cordova
          rm -rf www
          
          # 4. Copy your actual code files and assets (which are currently one directory up)
          # into the new temp_app directory.
          cp -r ../* .
          
          # 5. Rerun the Cordova prepare command to generate the necessary 'www' content
          cordova prepare
          
          # 6. Delete the unnecessary node_modules and temp files from the root
          rm -rf node_modules
          rm -rf temp_app/
          
      - name: Add Android Platform
        # This command now runs inside the temp_app directory, where config.xml exists
        script: cordova platform add android@$CORDOVA_ANDROID_VERSION

      - name: Build the Android Debug APK
        script: |
          # The compilation command runs inside the temp_app directory
          cordova build android --debug
          
          # Move artifacts (APK) back to the root ($CM_BUILD_DIR) for output
          cp platforms/android/app/build/outputs/apk/debug/app-debug.apk $CM_BUILD_DIR/
          
    # --- Artifacts (Output) ---
    artifacts:
      - "*.apk" 
      - platforms/android/app/build/outputs/**/*.apk
      
