workflows:
  android-debug:
    name: Cordova Android Debug Build – cordova-android@12.0.1
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      vars:
        CORDOVA_ANDROID_VERSION: "12.0.1"
      node: latest

    triggering:
      events:
        - push
        - tag
        - pull_request
      branch_patterns:
        - pattern: "*"
          include: true
          source: true

    scripts:
      - name: Install project dependencies
        script: |
          npm install   # safe even if package.json is tiny or missing deps

      - name: Install Cordova CLI (latest = 13.x, fully compatible)
        script: |
          npm install -g cordova

      - name: Install exact Android SDK components required by cordova-android@12
        script: |
          echo y | $ANDROID_HOME/tools/bin/sdkmanager --licenses >/dev/null
          $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --install \
            "build-tools;33.0.2" \
            "platforms;android-34" \
            "platform-tools" \
            "cmdline-tools;latest"

      - name: Add Android platform cordova-android@12.0.1
        script: |
          cordova telemetry off
          cordova platform rm android || true
          cordova platform add android@$CORDOVA_ANDROID_VERSION

      - name: Make gradlew executable (never upgrade it!)
        script: |
          cd platforms/android && chmod +x gradlew 2>/dev/null || true && cd ../..

      - name: Build Debug APK
        script: |
          cordova build android --debug --verbose --device

    artifacts:
      - platforms/android/app/build/outputs/apk/debug/app-debug.apk

    # ← Completely remove the publishing block if you don't use it
    # (Codemagic throws validation error when `email` exists but `recipients` is missing)

    # If you DO want email notifications, uncomment and add your email:
    # publishing:
    #   email:
    #     recipients:
    #       - your-real-email@example.com
    #     notify:
    #       success: true
    #       failure: true
