    # --- Build Steps (FINAL, CORRECTED SEQUENCE) ---
    scripts:
      - name: Install Cordova CLI
        script: npm install -g cordova

      - name: Create Project Structure and Move Files
        script: |
          # 1. Initialize the Cordova Project in a directory named 'project'
          cordova create project com.forge.alchemist "The Alchemist's Forge"
          
          # 2. Clean the project's boilerplate www folder
          rm -rf project/www/*
          
          # 3. Copy ALL your game files and assets from the repository root ($CM_BUILD_DIR) 
          # into the project's required www folder.
          cp -r $CM_BUILD_DIR/* project/www/
          
          # 4. Move the config.xml (which Cordova created) to the desired location (root of the project folder)
          mv project/www/config.xml project/
          
          # 5. CRITICAL STEP: Change directory into the project folder.
          # All subsequent steps will run *inside* this valid Cordova project.
          cd project
          
      - name: Add Android Platform
        # This command runs inside the 'project' directory where config.xml now sits
        script: cordova platform add android@$CORDOVA_ANDROID_VERSION

      - name: Build the Android Debug APK
        script: |
          # The compilation command runs inside the 'project' directory
          cordova build android --debug
          
          # Move artifacts (APK) back to the root ($CM_BUILD_DIR) for output
          cp platforms/android/app/build/outputs/apk/debug/app-debug.apk $CM_BUILD_DIR/
          
    # --- Artifacts (Output) ---
    artifacts:
      - "*.apk" 
      - platforms/android/app/build/outputs/**/*.apk
