version: 1.0.0

trigger:
  branch:
    - master
    - main

workflows:
  android-alpha-build:
    name: Android Alpha Build (Cordova)
    instance_type: mac_mini_m2
    environment:
      java: 17
      node: 18
      vars:
        CORDOVA_ANDROID_VERSION: "12.0.1"

    scripts:
      - name: Install Cordova CLI
        script: |
          npm install -g cordova

      - name: Install Android SDK Tools
        script: |
          brew install --cask android-commandlinetools || true
          export ANDROID_HOME="$HOME/Library/Android/sdk"
          export PATH="$ANDROID_HOME/cmdline-tools/latest/bin:$PATH"
          export PATH="$ANDROID_HOME/platform-tools:$PATH"
          echo "y" | sdkmanager --sdk_root=$ANDROID_HOME "platform-tools" "platforms;android-34" "build-tools;34.0.0" || true
          echo "y" | sdkmanager --licenses || true

      - name: Prepare Cordova Android Platform
        script: |
          rm -rf platforms/android || true
          cordova platform add android@$CORDOVA_ANDROID_VERSION

      - name: Build APK (Debug with full logs)
        script: |
          export JAVA_HOME=$(/usr/libexec/java_home -v 17)
          cd platforms/android
          ./gradlew assembleDebug --stacktrace --warning-mode all
          cd ../..

      - name: Locate & copy APK artifact
        script: |
          APK_PATH=$(find platforms/android/app/build/outputs/apk/debug -name "*.apk" | head -1)
          echo "APK found at: $APK_PATH"
          cp "$APK_PATH" app-debug.apk

    artifacts:
      - app-debug.apk
      - platforms/android/app/build/outputs/**/*.apk
