# 1. MANDATORY ROOT KEY: Defines the YAML version
version: 1.0.0
trigger:
  branch:
    - master
    - main

# 2. MANDATORY ROOT KEY: Defines the build pipelines
workflows:
  android-alpha-build:
    name: Android Alpha Build (Cordova - No GPG)
    instance_type: mac_mini_m2
    environment:
      java: 21 
      node: 18
      vars:
        CORDOVA_ANDROID_VERSION: "12.0.0" 

   # --- Build Steps (FINAL, STABLE SEQUENCE) ---
    scripts:
      - name: Full Android Build Pipeline
        script: |
          # 1. Install Cordova CLI
          npm install -g cordova
          
          # 2. Initialize the Cordova Project in a directory named 'project'
          cordova create project com.forge.alchemist "The Alchemist's Forge"
          
          # 3. CRITICAL: Move into the new project root
          cd project
          
          # 4. Clean and populate the project's www folder with source files
          rm -rf www/*
          cp -r $CM_BUILD_DIR/* www/
          
          # 5. Add Android Platform (This command is now run inside the valid 'project' directory)
          cordova platform add android@$CORDOVA_ANDROID_VERSION
          
          # 6. Execute the build command (This will likely fail, but it starts the process)
          cordova build android --debug
          
          # 7. CRITICAL FIX: Find the APK file path. The actual path is often one level deeper,
          # so we search for the file using 'find' to confirm the path, then copy it.
          # We use a wildcard search to find the debug APK regardless of the platform structure.
          
          echo "Attempting to locate and copy the generated APK file..."
          
          APK_PATH=$(find platforms/android/ -name "app-debug.apk")
          
          if [ -f "$APK_PATH" ]; then
            echo "SUCCESS: Found APK at $APK_PATH"
            # Copy the found APK to the root directory for Codemagic to pick up
            cp "$APK_PATH" $CM_BUILD_DIR/
          else
            echo "ERROR: Failed to locate app-debug.apk after build."
            exit 1 # Fail the script if the APK is not found
          fi
