workflows:
  android-debug:
    name: Cordova Android Debug Build ⚡ cordova-android@12.0.1 (CLI 13)
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      vars:
        CORDOVA_ANDROID_VERSION: "12.0.1"
        CORDOVA_CLI_VERSION: "latest"  # CLI 13.0.0 as of Dec 2025
      node: latest  # >=20.17.0 for CLI 13

    triggering:
      events:
        - push
        - tag
        - pull_request
      branch_patterns:
        - pattern: "*"
          include: true
          source: true

    scripts:
      - name: Install app dependencies (generates package-lock.json)
        script: |
          npm install  # Use 'install' not 'ci' – no lockfile on fresh clone

      - name: Install Cordova CLI globally (v13 latest)
        script: |
          npm install -g cordova@$CORDOVA_CLI_VERSION

      - name: Accept licenses + install EXACT required SDKs (build-tools 33.0.2)
        script: |
          echo y | $ANDROID_HOME/tools/bin/sdkmanager --licenses >/dev/null
          $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --install \
            "build-tools;33.0.2" \
            "platforms;android-34" \
            "platform-tools" \
            "cmdline-tools;latest"

      - name: Add Android platform (cordova-android@12.0.1)
        script: |
          cordova telemetry off
          cordova platform rm android || true
          cordova platform add android@$CORDOVA_ANDROID_VERSION

      - name: Ensure gradlew executable (no upgrades – sticks to Gradle 7.6)
        script: |
          cd platforms/android
          chmod +x gradlew 2>/dev/null || true
          cd ../..

      - name: Build Debug APK (Cordova CLI handles it reliably)
        script: |
          cordova build android --debug --verbose --device

    artifacts:
      - platforms/android/app/build/outputs/apk/debug/app-debug.apk

    publishing:
      email:
        notify:
          success: true
          failure: false
