# 1. MANDATORY ROOT KEY: Defines the YAML version
version: 1.0.0
trigger:
  branch:
    - master
    - main

# 2. MANDATORY ROOT KEY: Defines the build pipelines
workflows:
  android-alpha-build:
    name: Android Alpha Build (Cordova - No GPG)
    instance_type: mac_mini_m2
    environment:
      java: 21 
      node: 18
      vars:
        CORDOVA_ANDROID_VERSION: "12.0.0" 

    # --- Build Steps (FINAL, SINGLE-SCRIPT SEQUENCE) ---
    scripts:
      - name: Full Build Pipeline
        script: |
          # 1. Install Cordova CLI
          npm install -g cordova
          
          # 2. Initialize the Cordova Project in a directory named 'project'
          cordova create project com.forge.alchemist "The Alchemist's Forge"
          
          # 3. CRITICAL: Move into the new project and run all subsequent commands from here.
          cd project
          
          # 4. Clean the boilerplate www folder created by Cordova
          rm -rf www/*
          
          # 5. Copy your actual game files from the repository root (../) 
          # into the project's required www folder.
          cp -r ../* www/
          
          # 6. Move config.xml (which Cordova created) to the root of the project
          mv www/config.xml . 
          
          # 7. Add Android Platform (This command is now run inside the valid 'project' directory)
          cordova platform add android@$CORDOVA_ANDROID_VERSION
          
          # 8. Build the Android Debug APK
          cordova build android --debug
          
          # 9. Move artifacts (APK) back to the root ($CM_BUILD_DIR) for output
          cp platforms/android/app/build/outputs/apk/debug/app-debug.apk $CM_BUILD_DIR/
          
          # Clean up unnecessary files
          rm -rf www/node_modules

    # --- Artifacts (Output) ---
    artifacts:
      - "*.apk" 
      - platforms/android/app/build/outputs/**/*.apk
      
