# 1. MANDATORY ROOT KEY: Defines the YAML version
version: 1.0.0
trigger:
  branch:
    - master
    - main

# 2. MANDATORY ROOT KEY: Defines the build pipelines
workflows:
  android-alpha-build:
    name: Android Alpha Build (Cordova - No GPG)
    instance_type: mac_mini_m2
    environment:
      java: 21 
      node: 18
      vars:
        CORDOVA_ANDROID_VERSION: "12.0.0" 

    # --- Build Steps (FINAL, STABLE SEQUENCE) ---
    scripts:
      - name: Install Cordova CLI and Dependencies
        script: |
          npm install -g cordova
          
          # 1. Initialize the Cordova Project in a directory named 'project'
          cordova create project com.forge.alchemist "The Alchemist's Forge"
          
          # 2. CRITICAL: Move into the new project root
          cd project
          
          # 3. Clean and populate the project's www folder with source files
          rm -rf www/*
          cp -r $CM_BUILD_DIR/* www/
          
          # 4. Install the Android platform
          cordova platform add android@$CORDOVA_ANDROID_VERSION
          
      - name: Build the Android Debug APK and Find Artifact
        script: |
          # Ensure we are in the project root before building
          cd project
          
          # 1. Execute the build command
          cordova build android --debug
          
          # 2. CRITICAL FIX: The successful APK is located in: 
          # platforms/android/app/build/outputs/apk/debug/app-debug.apk
          # We copy it back to the Codemagic root ($CM_BUILD_DIR)
          cp platforms/android/app/build/outputs/apk/debug/app-debug.apk $CM_BUILD_DIR/
          
    # --- Artifacts (Output) ---
    artifacts:
      - "*.apk"
      
