workflows:
  android-debug:
    name: Cordova Android Debug Build ⚡ cordova-android@12
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      vars:
        CORDOVA_ANDROID_VERSION: "12.0.1"
      node: latest

    triggering:
      events:
        - push
        - tag
        - pull_request
      branch_patterns:
        - pattern: "*"
          include: true
          source: true

    scripts:
      - name: Install Cordova + dependencies
        script: |
          npm ci
          npm install -g cordova@$CORDOVA_ANDROID_VERSION

      - name: Accept licenses + install EXACT required SDKs (33.0.2 !!)
        script: |
          echo y | $ANDROID_HOME/tools/bin/sdkmanager --licenses >/dev/null
          $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --install \
            "build-tools;33.0.2" \
            "platforms;android-34" \
            "platform-tools" \
            "cmdline-tools;latest"

      - name: Add Android platform (cordova-android 12)
        script: |
          cordova telemetry off
          cordova platform rm android || true
          cordova platform add android@$CORDOVA_ANDROID_VERSION

      - name: DO NOT upgrade Gradle wrapper → keep 7.6 (required for cordova-android@12)
        script: |
          # Absolutely critical: cordova-android 12 breaks with Gradle 8+
          # Just make sure gradlew is executable
          cd platforms/android
          chmod +x gradlew 2>/dev/null || true
          cd ../..

      - name: Build Debug APK (using Cordova directly – most reliable)
        script: |
          cordova build android --debug --verbose --device

    artifacts:
      - platforms/android/app/build/outputs/apk/debug/app-debug.apk

    publishing:
      email:
        recipients:
          - your-email@example.com
        notify:
          success: true
          failure: false
