version: 1.0.0

trigger:
  branch:
    - master
    - main

workflows:
  android-alpha-build:
    name: Android Alpha Build (Cordova)
    instance_type: mac_mini_m2
    environment:
      java: 21
      node: 18
      android: 34
      vars:
        CORDOVA_ANDROID_VERSION: "12.0.0"

    scripts:
      - name: Install Cordova CLI
        script: |
          npm install -g cordova

      - name: Prepare project (make sure android platform exists)
        script: |
          if [ ! -d "platforms/android" ]; then
            cordova platform add android@$CORDOVA_ANDROID_VERSION
          else
            cordova prepare android
          fi

      - name: Build APK
        script: |
          cordova build android --debug

      - name: Copy APK artifact
        script: |
          APK_PATH=$(find platforms/android/app/build/outputs/apk/debug -name "*.apk" | head -1)
          echo "APK_PATH: $APK_PATH"

          if [ -f "$APK_PATH" ]; then
            cp "$APK_PATH" app-debug.apk
            echo "APK copied successfully!"
          else
            echo "APK NOT FOUND — build likely failed!"
            exit 1
          fi

    artifacts:
      - app-debug.apk
      - platforms/android/app/build/outputs/**/*.apk
