workflows:
  android-alpha-build:
    name: Android Alpha Build (Cordova)
    instance_type: mac_mini_m2 # Fast machine for quick build
    environment:
      # Removed the problematic 'android: 34' line
      java: 21 # Ensure the correct JDK is used
      node: 18
      # Set the Cordova platform version to match the installed SDK (Optional, for older versions)
      vars:
        CORDOVA_ANDROID_VERSION: "12.0.0" 

    # --- Build Steps ---
    scripts:
      - name: Install Cordova CLI
        script: npm install -g cordova

      - name: Install Plugins (GPG, etc.)
        script: |
          # Install your GPG plugin and dependencies
          cordova plugin add cordova-plugin-googleplayservices
          cordova plugin add com.sreedesg.cordova.gpg --variable GPG_APP_ID="YOUR_GPG_APP_ID"
          # NOTE: REPLACE YOUR_GPG_APP_ID with your actual numeric ID

      - name: Add Android Platform
        # Use the variable set above to ensure compatibility
        script: cordova platform add android@$CORDOVA_ANDROID_VERSION

      - name: Build the Android Debug APK
        # This command runs Gradle and generates the APK
        script: cordova build android --debug --buildConfig=build.json

    # --- Artifacts (Output) ---
    artifacts:
      - platforms/android/app/build/outputs/**/*.apk

    # --- Publishing ---
    # Optional: Set up email publishing here
    
